# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dimuth De Zoysa\Desktop\Python_projects\emailvalidate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window1(object):
    def setupUi(self, Window1):
        Window1.setObjectName("Window1")
        Window1.resize(320, 240)
        Window1.setAutoFillBackground(False)
        self.btnClear = QtWidgets.QPushButton(Window1)
        self.btnClear.setGeometry(QtCore.QRect(50, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.btnClear.setFont(font)
        self.btnClear.setCheckable(False)
        self.btnClear.setObjectName("btnClear")
        self.btnValidate = QtWidgets.QPushButton(Window1)
        self.btnValidate.setGeometry(QtCore.QRect(170, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        self.btnValidate.setFont(font)
        self.btnValidate.setDefault(True)
        self.btnValidate.setFlat(False)
        self.btnValidate.setObjectName("btnValidate")
        self.txtEmail = QtWidgets.QLineEdit(Window1)
        self.txtEmail.setGeometry(QtCore.QRect(50, 100, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.txtEmail.setFont(font)
        self.txtEmail.setText("")
        self.txtEmail.setObjectName("txtEmail")
        self.lbl_headline = QtWidgets.QLabel(Window1)
        self.lbl_headline.setGeometry(QtCore.QRect(60, 30, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.lbl_headline.setFont(font)
        self.lbl_headline.setObjectName("lbl_headline")

        self.retranslateUi(Window1)
        QtCore.QMetaObject.connectSlotsByName(Window1)
        Window1.setTabOrder(self.txtEmail, self.btnClear)
        Window1.setTabOrder(self.btnClear, self.btnValidate)

    def retranslateUi(self, Window1):
        _translate = QtCore.QCoreApplication.translate
        Window1.setWindowTitle(_translate("Window1", "Dialog"))
        self.btnClear.setText(_translate("Window1", "Clear"))
        self.btnValidate.setText(_translate("Window1", "Validate"))
        self.lbl_headline.setText(_translate("Window1", "Emai Address Vaidation "))
